[[Snippets]]
  Description = "List Models (Ollama)"
  Output = ""
  Tag = ["ollama", "models"]
  command = "ollama list"

[[Snippets]]
  Description = "List Packages (Brew)"
  Output = ""
  Tag = ["brew", "packages"]
  command = "brew list"

[[Snippets]]
  Description = "List Packages (Cargo)"
  Output = ""
  Tag = ["cargo", "packages"]
  command = "cargo install --list"

[[Snippets]]
  Description = "List Packages (Golang)"
  Output = ""
  Tag = ["golang", "packages"]
  command = "gup list"

[[Snippets]]
  Description = "List Packages (Mac App Store)"
  Output = ""
  Tag = ["mas", "packages"]
  command = "mas list"

[[Snippets]]
  Description = "List Packages (NPM)"
  Output = ""
  Tag = ["npm", "packages"]
  command = "npm list -g --depth=0"

[[Snippets]]
  Description = "List Packages (Python)"
  Output = ""
  Tag = ["pipx", "packages"]
  command = "pipx list"

[[Snippets]]
  Description = "Remove all resources from a Tofu state"
  Output = ""
  Tag = ["terraform", "tofu"]
  command = "tofu state list | xargs -n1 tofu state rm"

[[Snippets]]
  Description = "Sync Chezmoi-managed Files (Pull)"
  Output = ""
  Tag = ["chezmoi"]
  command = "chezmoi update --apply"

[[Snippets]]
  Description = "Sync Chezmoi-managed Files (Push)"
  Output = ""
  Tag = ["chezmoi"]
  command = "set original_pwd (pwd); cd ~ && chezmoi managed -i files | xargs -n1 chezmoi re-add; cd $original_pwd; set -e original_pwd"

[[Snippets]]
  Description = "Update Models (Ollama)"
  Output = ""
  Tag = ["ollama", "update"]
  command = "for model in (ollama list | tail -n +2 | awk '{print $1}'); ollama pull $model; end"

[[Snippets]]
  Description = "Update Packages (All)"
  Output = ""
  Tag = ["brew", "cargo", "golang", "pipx", "mas", "npm", "update"]
  command = "set -l names; set -l commands; for name in (pet list --tags update-all | grep '^ *Description:' | sed 's/^ *Description: //'); set -a names (string replace -a , ';' -- $name); end; for cmd in (pet list --tags update-all | grep '^ *Command:' | sed 's/^ *Command: //'); set -a commands \"$cmd\"; end; if test (count $commands) -eq 0; echo 'No update-all snippets found'; exit 1; end; mprocs $commands --names (string join , $names); set -e names; set -e commands; set -e name; set -e cmd"

[[Snippets]]
  Description = "Update Packages (Brew)"
  Output = ""
  Tag = ["brew", "packages", "update", "update-all"]
  command = "brew update && brew upgrade && brew cleanup --prune=all"

[[Snippets]]
  Description = "Update Packages (Cargo)"
  Output = ""
  Tag = ["cargo", "update", "update-all"]
  command = "ls ~/.cargo/bin | awk '{print $NF}' | xargs -I{} cargo install {} --locked"

[[Snippets]]
  Description = "Update Packages (Golang)"
  Output = ""
  Tag = ["golang", "update", "update-all"]
  command = "gup update"

[[Snippets]]
  Description = "Update Packages (Mac App Store)"
  Output = ""
  Tag = ["mas", "update", "update-all"]
  command = "mas upgrade"

[[Snippets]]
  Description = "Update Packages (NPM)"
  Output = ""
  Tag = ["npm", "update", "update-all"]
  command = "npm update -g"

[[Snippets]]
  Description = "Update Packages (Python)"
  Output = ""
  Tag = ["pipx", "update", "update-all"]
  command = "pipx upgrade-all"

[[Snippets]]
  Description = "Update Schemas (Archy)"
  Output = ""
  Tag = ["archy", "genesys",  "update"]
  command = "mprocs (gc profiles list | jq -r '.[] | \"archy refresh --location \\(.environment) --clientId \\(.clientName) --clientSecret \\(.clientSecret) --outputDir ~/.archy/\\(.profileName)\"') --names (gc profiles list | jq -r '.[].profileName' | string join ,)"
