
[[Snippets]]
  Description = "Update Installed Packages (All)"
  Output = ""
  Tag = []
  command = "brew update && brew upgrade && brew cleanup --prune=all && ls ~/.cargo/bin | awk '{print $NF}' | xargs -I{} cargo install {} --locked && pipx upgrade-all"

[[Snippets]]
  Description = "Update Installed Packages (Brew)"
  Output = ""
  Tag = []
  command = "brew update && brew upgrade && brew cleanup --prune=all"

[[Snippets]]
  Description = "Update Installed Packages (Cargo)"
  Output = ""
  Tag = []
  command = "ls ~/.cargo/bin | awk '{print $NF}' | xargs -I{} cargo install {} --locked"

[[Snippets]]
  Description = "Update Installed Packages (Python)"
  Output = ""
  Tag = []
  command = "pipx upgrade-all"

[[Snippets]]
  Description = "Re-Add All Chezmoi-managed Files"
  Output = ""
  Tag = []
  command = "set original_pwd (pwd); cd ~ && chezmoi managed -i files | xargs -n1 chezmoi re-add; cd $original_pwd; set -e original_pwd"
