return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "windwp/nvim-ts-autotag",
  },
  build = ":TSUpdate",
  event = {
    "BufReadPre",
    "BufNewFile"
  },
  config = function()
    local treesitter = require("nvim-treesitter.configs")
    treesitter.setup({
      ensure_installed = {
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "dot",
        "erlang",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "groovy",
        "hcl",
        "helm",
        "html",
        "http",
        "java",
        "javascript",
        "jq",
        "json",
        "kotlin",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "muttrc",
        "pem",
        "perl",
        "php",
        "python",
        "regex",
        "ruby",
        "rust",
        "scala",
        "sql",
        "ssh_config",
        "swift",
        "tcl",
        "terraform",
        "tmux",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml"
      },
      autotag = { enable = true },
      highlight = { enable = true },
      indent = { enable = true },
    })
  end
}
