[keymap.scroll_keymap]
up = ["up", "k"]
down = ["down", "j"]
page_up = ["page_up", "u"]
page_down = ["page_down", "d"]
top = ["home", "g"]
bottom = ["end", "G"]

[keymap.story_view_keymap]
next_story = ["down", "j"]
prev_story = ["up", "k"]
next_page = ["right", "n"]
prev_page = ["left", "p"]

[theme.palette]
background = "#1a1b26"
foreground = "#c0caf5"
selection_background = "#33467c"
selection_foreground = "#c0caf5"
black = "#15161e"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"
light_black = "#414868"
light_white = "#c0caf5"
light_red = "#ff7a93"
light_magenta = "#c0a9f5"
light_green = "#b9f27c"
light_cyan = "#a4f9ef"
light_blue = "#7da6ff"
light_yellow = "#ff9e64"

[theme.component_style]
title_bar = { back = "#7aa2f7", effect = "bold" }
matched_highlight = { front = "#1a1b26", back = "#e0af68"}
metadata = { front = "#9aa5ce" }
username = { effect = "bold" }
loading_bar = { front = "#e0af68", back = "#7aa2f7" }
header = { front = "#c0caf5", effect = "bold" }
quote = { front = "#9aa5ce" }
italic = { effect = "italic" }
bold = { effect = "bold" }
single_code_block = { front = "#c0caf5", back = "#2e3440" }
multiline_code_block = { front = "#9aa5ce", effect = "bold" }
link = { front = "#7dcfff" }
link_id = { front = "#1a1b26", back = "#e0af68" }
current_story_tag = { front = "#c0caf5" }
ask_hn = { front = "#f7768e", effect = "bold" }
tell_hn = { front = "#e0af68", effect = "bold" }
show_hn = { front = "#7aa2f7", effect = "bold" }
launch_hn = { front = "#9ece6a", effect = "bold" }
